apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: bgd-rollouts
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bgd
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause:
            duration: 30s
        - setWeight: 40
        - pause:
            duration: 30s
        - setWeight: 60
        - pause:
            duration: 30s
        - setWeight: 80
        - pause:
            duration: 30s
        - setWeight: 100
  template:
    metadata:
      labels:
        app: bgd
    spec:
      containers:
        - name: bgd
          image: rayjang111/bgd:1.0.0
          env:
            - name: COLOR
              value: "green"
          resources: {}